### ISSUE TITLE
Most icons not displayed in program menu

### ISSUE THREAD

**Issue by nextstopsun** [qgis/homebrew-qgisdev#8]
There aren't really any icons in QGIS program menu. In my case only "Project properties" and "Raster calculator" icons are displayed.
<img width="241" alt="screen shot 2016-12-10 at 13 59 16" src="https://cloud.githubusercontent.com/assets/966321/21072914/7ab8c5aa-bee2-11e6-811e-43a848ecf421.png">

Most menu icons are displayed as png, so they look pixelated on retina HiDPI display.
<img width="404" alt="screen shot 2016-12-10 at 14 00 22" src="https://cloud.githubusercontent.com/assets/966321/21072923/b956ffca-bee2-11e6-95c7-d4202374f9dc.png">

But in some cases (Project properties window) svg icons are displayed.
<img width="151" alt="screen shot 2016-12-10 at 13 59 54" src="https://cloud.githubusercontent.com/assets/966321/21072928/dfcb3de2-bee2-11e6-80ca-f732d8a32bf8.png">

I guess it's just a minor bug with paths to SVG icons.

**Comment by dakcarto** [comment]
Hi @nextstopsun, thanks for reporting!

Any core QGIS bug for a particular developer version, i.e. unrelated to its Homebrew formula here, should be [reported upstream at the QGIS project](https://www.qgis.org/en/site/getinvolved/development/bugreporting.html) or posted to the [QGIS developer mailing list](https://www.qgis.org/en/site/getinvolved/mailinglists.html).

Please reopen if you feel this bug is related to the Homebrew formula.

**Comment by dakcarto** [comment]
See https://hub.qgis.org/issues/16016
